openapi: 3.0.3
info:
  title: API de Mensajería
  description: Endpoint para enviar mensajes de texto a través de WhatsApp.
  version: 1.0.0

servers:
  - url: https://apievo.qr.buho.la
    description: Servidor de producción

tags:
  - name: api
    description: Enviar Mensajes
    externalDocs:
      description: Más
      url: https://apievo.qr.buho.la

paths:
  /api/message/send-text:
    post:
      tags:
        - api
      summary: Enviar mensaje de texto por WhatsApp
      operationId: enviarMensaje
      description: Permite enviar un mensaje de texto a un número de WhatsApp.
      requestBody:
        description: Datos necesarios para enviar el mensaje.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnviarMensajeRequest"
      responses:
        "200":
          description: Mensaje enviado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autorizado (Token incorrecto o ausente)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    EnviarMensajeRequest:
      type: object
      properties:
        number:
          type: string
          example: "123456789"
          description: Número de teléfono en formato internacional sin el "+".
        message:
          type: string
          example: "Plain text message"
          description: Mensaje de texto a enviar.
    
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            key:
              type: object
              properties:
                remoteJid:
                  type: string
                  example: "51123456789@s.whatsapp.net"
                fromMe:
                  type: boolean
                  example: true
                id:
                  type: string
                  example: "BAE51C2115EE6FC0"
            message:
              type: object
              properties:
                extendedTextMessage:
                  type: object
                  properties:
                    text:
                      type: string
                      example: "Plain text message"
                    contextInfo:
                      type: array
                      items:
                        type: object
            messageTimestamp:
              type: string
              example: "1726586899"
            status:
              type: string
              example: "PENDING"
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Descripción del error"
