openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Cotización
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/retentions:
    post:
      tags:
        - api
      summary: GENERAR COMPROBANTE DE RETENCIÓN
      description: |  
        Es una constancia de que alguna persona moral te retuvo algún tipo de impuesto, (relativo al Impuesto Sobre la Renta), 
        y sirve para demostrar que dicho impuesto te fue retenido, y presentarlo a la autoridad fiscal en caso que te sea requerido.  

        Para generar un comprobante de retención puede usar el siguiente servicio, necesitará la url, el token, y los datos del documento.  


        ***Ejemplo:***  
         - **URL:** https://empresa1.pro7.uio.la/api/retentions  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt

      operationId: generarComprobanteRetencion
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de GENERAR COMPROBANTE DE RETENCIÓN
components:
  schemas:
    Pet:
      type: object
      properties:
        serie_documento:
          type: string
          example: "R001"
        numero_documento:
          type: string
          example: "#"
        fecha_de_emision:
          type: string
          format: date
          example: "2018-10-09"
        hora_de_emision:
          type: string
          format: time
          example: "10:11:11"
        codigo_tipo_documento:
          type: string
          example: "20"
        datos_del_emisor:
          type: object
          properties:
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
            codigo_del_domicilio_fiscal:
              type: string
              example: "0000"
        datos_del_proveedor:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            numero_documento:
              type: string
              example: "10414711225"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            nombre_comercial:
              type: string
              example: "EMPRESA XYZ"
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
        codigo_tipo_retencion:
          type: string
          example: "01"
        observaciones:
          type: string
          example: "-"
        totales:
          type: object
          properties:
            total_retenido:
              type: number
              format: float
              example: 30.00
            total_pagado:
              type: number
              format: float
              example: 1000.00
        documentos:
          type: array
          items:
            type: object
            properties:
              codigo_tipo_documento:
                type: string
                example: "01"
              serie_documento:
                type: string
                example: "F001"
              numero_documento:
                type: string
                example: "3"
              fecha_de_emision:
                type: string
                format: date
                example: "2018-10-09"
              codigo_tipo_moneda:
                type: string
                example: "PEN"
              pagos:
                type: array
                items:
                  type: object
                  properties:
                    fecha_de_pago:
                      type: string
                      format: date
                      example: "2018-10-09"
                    total_pago:
                      type: number
                      format: float
                      example: 200.00
                    codigo_tipo_moneda:
                      type: string
                      example: "PEN"
              tipo_de_cambio:
                type: object
                properties:
                  codigo_tipo_moneda_referencia:
                    type: string
                    example: "PEN"
                  codigo_tipo_moneda_objetivo:
                    type: string
                    example: "PEN"
                  factor:
                    type: number
                    format: float
                    example: 1
                  fecha_tipo_de_cambio:
                    type: string
                    format: date
                    example: "2018-10-09"
              fecha_de_retencion:
                type: string
                format: date
                example: "2018-10-09"
              total_documento:
                type: number
                format: float
                example: 400.00
              total_retenido:
                type: number
                format: float
                example: 12.00
              total_a_pagar:
                type: number
                format: float
                example: 412.00
              total_pagado:
                type: number
                format: float
                example: 412.00
        
      

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "R001-3"
            filename:
              type: string
              example: "11111111111-20-R001-3"
            external_id:
              type: string
              example: "9d997b38-92a6-42f2-b827-4b73ec5ca1a3"
        links:
          type: object
          properties:
            xml:
              type: string
              format: uri
              example: "https://empresa1.pro7.uio.la/downloads/retention/xml/9d997b38-92a6-42f2-b827-4b73ec5ca1a3"
            pdf:
              type: string
              format: uri
              example: "https://empresa1.pro7.uio.la/downloads/retention/pdf/9d997b38-92a6-42f2-b827-4b73ec5ca1a3"
            cdr:
              type: string
              format: uri
              example: "https://empresa1.pro7.uio.la/downloads/retention/cdr/9d997b38-92a6-42f2-b827-4b73ec5ca1a3"
        response:
          type: object
          properties:
            code:
              type: string
              example: "0"
            description:
              type: string
              example: "El Comprobante numero R001-3 ha sido aceptado"
            notes:
              type: array
              items:
                type: string
                example: []
           

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header