openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/dispatches:
    post:
      tags:
        - api
      summary: Generar Guia de Remisión - Transportista
      description: |  
        Para generar una guia de remision de transportista puede usar el siguiente servicio, necesitará la url, el token, y los datos del documento.  

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.pro7.uio.la/api/dispatches 
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt  

         **NOTA:**  
         El Chofer y el Vehículo son campos obligatorios. Sin embargo, el Chofer Secundario y el Vehículo Secundario son opcionales, y pueden ser omitidos.

      operationId: generarGuiaRemisionTransportista
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de GENERAR GUIA DE REMISIÓN - TRANSPORTISTA
components:
  schemas:
    Pet:
      type: object
      properties:
        serie_documento:
          type: string
          example: "T001"
        numero_documento:
          type: string
          example: "#"
        fecha_de_emision:
          type: string
          format: date
          example: "2024-11-12"
        hora_de_emision:
          type: string
          format: time
          example: "10:11:11"
        codigo_tipo_documento:
          type: string
          example: "09"
        datos_del_emisor:
          type: object
          properties:
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
            codigo_del_domicilio_fiscal:
              type: string
              example: "0000"
        datos_del_cliente_o_receptor:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            numero_documento:
              type: string
              example: "10414711225"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            nombre_comercial:
              type: string
              example: "EMPRESA XYZ S.A."
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
        observaciones:
          type: string
          example: "aaaaaaaaaaaaaaa"
        codigo_modo_transporte:
          type: string
          example: "01"
        codigo_motivo_traslado:
          type: string
          example: "01"
        descripcion_motivo_traslado:
          type: string
          example: "El cliente solicito envia a su trabajo en ..."
        fecha_de_traslado:
          type: string
          format: date
          example: "2024-11-12"
        codigo_de_puerto:
          type: string
          example: ""
        indicador_de_transbordo: 
          type: boolean
          example: false
        unidad_peso_total:
          type: string
          example: "KGM"
        peso_total:
          type: number
          example: 30.00
        numero_de_bultos:
          type: number
          example: 1
        numero_de_contenedor:
          type: string
          example: ""
        direccion_partida:
          type: object
          properties:
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "PUNTO A"
            codigo_del_domicilio_fiscal:
              type: string
              example: ""
        direccion_llegada:
          type: object
          properties:
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "PUNTO 2"
            codigo_del_domicilio_fiscal:
              type: string
              example: ""
        transportista:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            numero_documento:
              type: string
              example: "10417844398"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "aaaaaaaaa"
            numero_mtc:
              type: string
              example: ""
        chofer:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "1"
            numero_documento:
              type: string
              example: "4177874"
            nombres:
              type: string
              example: "Juan Perez"
            numero_licencia:
              type: string
              example: "A76023452"
            telefono:
              type: string
              example: "923131232"
        chofer_secundario:
          type: array
          items:
            type: object
            properties:
              codigo_tipo_documento_identidad:
                type: string
                example: "1"
              numero_documento:
                type: string
                example: "41778243"
              nombres:
                type: string
                example: "Nombres y apellidos 1"
              numero_licencia:
                type: string
                example: "A76023452"
              telefono:
                type: string
                example: ""
        vehiculo:
          type: object
          properties:
            numero_de_placa:
              type: string
              example: "A011254"
            certificado_habilitacion_vehicular:
              type: string
              example: "1212121212"
            modelo:
              type: string
              example: "YARIS"
            marca:
              type: string
              example: "TOYOTA"
        vehiculo_secundario:
          type: array
          items:
            type: object
            properties:
              numero_de_placa:
                type: string
                example: "A012254"
              certificado_habilitacion_vehicular:
                type: string
                example: "1212121212"
              modelo: 
                type: string
                example: "YARIS"
              marca: 
                type: string
                example: "TOYOTA"
        items:
          type: array
          items:
            type: object
            properties:
              codigo_interno:
                type: string
                example: "P0121"
              cantidad:
                type: number
                example: 2
        documento_afectado:
          type: object
          properties: 
            serie_documento:
              type: string
              example: "F001"
            numero_documento:
              type: string
              example: "190"
            codigo_tipo_documento:
              type: string
              example: "01"

      required:
        - serie_documento
        - datos_del_emisor
        - datos_del_cliente_o_receptor
        - direccion_partida
        - direccion_llegada
        - transportista
        - chofer
        - vehiculo

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "T001-6"
            filename:
              type: string
              example: "11111111111-09-T001-6"
            external_id:
              type: string
              example: "284a24e7-7997-4c91-83e5-34c92922cde0"
            

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header