openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/dispatches:
    post:
      tags:
        - api
      summary: Remitente | Transporte Privado
      description: |  
        Este tipo de transporte se refiere a los envíos realizados utilizando vehículos propios del remitente, como parte de su operación logística.
         En este caso, se debe especificar la información del conductor encargado del traslado y los datos del vehículo utilizado.  

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.pro7.uio.la/api/dispatches  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt  
      operationId: remitenteTransportePrivado
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de Remitente | Transporte privado
components:
  schemas:
    Pet:
      type: object
      properties:
        serie_documento:
          type: string
          example: "T001"
        numero_documento:
          type: string
          example: "#"
        fecha_de_emision:
          type: string
          format: date
          example: "2022-12-02"
        hora_de_emision:
          type: string
          format: time
          example: "10:11:11"
        codigo_tipo_documento:
          type: string
          example: "09"
        datos_del_emisor:
          type: object
          properties:
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
            codigo_del_domicilio_fiscal:
              type: string
              example: "0000"
        datos_del_cliente_o_receptor:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            numero_documento:
              type: string
              example: "20601274133"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            nombre_comercial:
              type: string
              example: "EMPRESA XYZ"
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
        observaciones:
          type: string
          example: "aaaaaaaaaaaaaaa"
        codigo_modo_transporte:
          type: string
          example: "02"
        codigo_motivo_traslado:
          type: string
          example: "05"
        descripcion_motivo_traslado:
          type: string
          example: "El cliente solicito envia a su trabajo en ..."
        fecha_de_traslado:
          type: string
          format: date
          example: "2022-12-02"
        codigo_de_puerto:
          type: string
          example: ""
        indicador_de_transbordo:
          type: boolean
          example: false
        unidad_peso_total:
          type: string
          example: "KGM"
        peso_total:
          type: number
          example: 30.00
        numero_de_bultos:
          type: number
          example: 1
        numero_de_contenedor:
          type: string
          example: ""
        direccion_partida:
          type: object
          properties:
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "PUNTO A"
            codigo_del_domicilio_fiscal:
              type: string
              example: "0000"
        direccion_llegada:
          type: object
          properties:
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "PUNTO 2"
            codigo_del_domicilio_fiscal:
              type: string
              example: "0000"
        chofer:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "1"
            numero_documento:
              type: string
              example: "41784439"
            nombres:
              type: string
              example: "JUAN"
            apellidos:
              type: string
              example: "PEREZ"
            numero_licencia:
              type: string
              example: "Q41784439"
        numero_de_placa:
          type: string
          example: "A011254"
        items:
          type: array
          items:
            type: object
            properties:
              codigo_interno:
                type: string
                example: "prueba"
              cantidad:
                type: number
                example: 2
        documento_afectado:
          type: object
          properties:
            serie_documento:
              type: string
              example: "F001"
            numero_documento:
              type: string
              example: "190"
            codigo_tipo_documento:
              type: string
              example: "01"
        documento_relacionado:
          type: array
          items:
            type: object
            properties:
              numero:
                type: string
                example: "F001-1"
              empresa:
                type: string
                example: "Empresa ABC"
              ruc:
                type: string
                example: "20123123123"
              documento:
                type: object
                properties:
                  id:
                    type: string
                    example: "09"
                  descripcion:
                    type: string
                    example: "Factura Electrónica"

      required:
        - serie_documento
        - datos_del_cliente_o_receptor
        - direccion_llegada
        - chofer
        - numero_de_placa

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "T001-18"
            filename:
              type: string
              example: "11111111111-09-T001-18"
            external_id:
              type: string
              example: "9f297a80-c4d0-4fca-9ec9-a81d4434fbbe"

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header