openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/dispatch-carrier:
    post:
      tags:
        - api
      summary: Transportista | Pagador Flete
      description: |  
        Aquí se muestra el proceso para generar Transportista con flete  

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.pro7.uio.la/api/dispatch-carrier 
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt  
      operationId: transportistaFlete
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de GENERAR GUIA DE REMISIÓN - FLETE
components:
  schemas:
    Pet:
      type: object
      properties:
        datos_del_emisor:
          type: object
          properties:
            codigo_pais:
              type: string
              example: "PE"
            ubigeo:
              type: string
              example: "150101"
            direccion:
              type: string
              example: "Av. 2 de Mayo"
            correo_electronico:
              type: string
              example: "demo@gmail.com"
            telefono:
              type: string
              example: "427-1148"
            codigo_del_domicilio_fiscal:
              type: string
              example: "0000"
        serie_documento:
          type: string
          example: "V001"
        numero_documento:
          type: string
          example: "#"
        codigo_tipo_documento:
          type: string
          example: "31"
        fecha_de_emision:
          type: string
          format: date
          example: "2022-12-14"
        hora_de_emision:
          type: string
          format: time
          example: "10:11:11"
        fecha_de_traslado:
          type: string
          format: date
          example: "2022-12-02"
        unidad_peso_total:
          type: string
          example: "KGM"
        peso_total:
          type: number
          example: 30.00
        observaciones:
          type: string
          example: "aaaaaaaaaaaaaaa"
        indicador_de_transbordo:
          type: boolean
          example: false
        datos_remitente:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            descripcion_tipo_documento_identidad:
              type: string
              example: "RUC"
            numero_documento:
              type: string
              example: "20601274133"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            nombre_comercial:
              type: string
              example: "EMPRESA XYZ"
        datos_destinatario:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "6"
            descripcion_tipo_documento_identidad:
              type: string
              example: "RUC"
            numero_documento:
              type: string
              example: "20601274133"
            apellidos_y_nombres_o_razon_social:
              type: string
              example: "EMPRESA XYZ S.A."
            nombre_comercial:
              type: string
              example: "EMPRESA XYZ"
        chofer:
          type: object
          properties:
            codigo_tipo_documento_identidad:
              type: string
              example: "1"
            numero_documento:
              type: string
              example: "41784439"
            nombres:
              type: string
              example: "JUAN"
            apellidos:
              type: string
              example: "PEREZ"
            numero_licencia:
              type: string
              example: "Q41784439"
        numero_de_placa:
          type: string
          example: "A011254"
        items:
          type: array
          items:
            type: object
            properties:
              codigo_interno:
                type: string
                example: "prueba"
              cantidad:
                type: number
                example: 2
        pagador_flete:
          type: object
          properties:
            indicador_pagador_flete:
              type: string
              example: "Remitente"
            codigo_tipo_documento_identidad:
              type: string
              example: "1"
            descripcion_tipo_documento_identidad:
              type: string
              example: "RUC"
            numero:
              type: string
              example: "20810001281"
            nombres:
              type: string
              example: "EMPRESA DEMO SAC"

      required:
        - serie_documento
        - datos_del_emisor
        - datos_del_cliente_o_receptor
        - direccion_partida
        - direccion_llegada
        - transportista
        - chofer
        - vehiculo

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "V001-11"
            filename:
              type: string
              example: "11111111111-09-V001-11"
            external_id:
              type: string
              example: "b8f5e270-f264-4017-a00f-7a3f7cb59862"
            

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header