openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Cotización
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
paths:
  /api/quotations/list:
    get:
      tags:
        - api
      summary: LISTA DE COTIZACIONES
      description: |  
        ***Ejemplo:***  
        - **Método:** GET  
        - **URL:** https://empresa1.pro7.uio.la/api/quotations/list 
        - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: listaCotizaciones
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
        '400':
          description: Invalid status value
      security:
        - fastura_auth:
            - write:pets
            - read:pets
          
# Formato Json de LISTA DE COTIZACIONES
components:
  schemas:
    Pet:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number_full:
              type: string
              example: "COT-8"
            external_id:
              type: string
              example: "25fd5675-1ad5-4e7b-9191-9ae4b7f1dde2"
            filename:
              type: string
              example: "COT-8-20241108"
            print_a4:
              type: string
              example: "https://empresa1.pro7.uio.la/quotations/print/25fd5675-1ad5-4e7b-9191-9ae4b7f1dde2/a4"
            print_ticket:
              type: string
              example: "https://empresa1.pro7.uio.la/quotations/print/25fd5675-1ad5-4e7b-9191-9ae4b7f1dde2/ticket"


    Response:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                example: 20
              items:
                type: string
                example: []
              order_note:
                type: string
                example: {}
              payment_method_type_id:
                type: string
                example: "10"
              soap_type_id:
                type: string
                example: "01"
              external_id:
                type: string
                example: "6012ffb7-a212-4a8b-8839-0e95374a9155"
              number_full:
                type: string
                example: "COT-20"
              date_of_issue:
                type: string
                format: date
                example: "2023-09-21"
              delivery_date: 
                type: string
                example:
              identifier:
                type: string
                example: "COT-20"
              user_name: 
                type: string
                example: "Administrador"
              seller_name:
                type: string
                example: "Administrador"
              customer_id:
                type: number
                example: 21
              customer_name:
                type: string
                example: "ALVAREZ MORENO JHEYSON ALBER"
              customer_number:
                type: string
                example: "10750058197"
              customer_telephone:
                type: number
                example:
              customer_email:
                type: string
                example:
              exchange_rate_sale:
                type: string
                example: "3.718"
              currency_type_id:
                type: string
                example: "PEN"
              total_exportation:
                type: string
                example: "0.00"
              total_free:
                type: string
                example: "0.00"
              total_unaffected:
                type: string
                example: "0.00"
              total_exonerated:
                type: string
                example: "0.00"
              total_taxed:
                type: string
                example: "132.73"
              total_igv:
                type: string
                example: "13.27"
              total:
                type: string
                example: "146.00"
              state_type_id:
                type: string
                example: "01"
              state_type_description:
                type: string
                example: "Registrado"
              documents:
                type: string
                example: []
              sale_notes:
                type: string
                example: []
              sale_opportunity_number_full:
                type: string
                example: 
              contract_number_full:
                type: string
                example: 
              sale_opportunity:
                type: string
                example: 
              btn_generate:
                type: boolean
                example: true
              btn_generate_cnt:
                type: boolean
                example: true
              btn_options:
                type: boolean
                example: true
              external_id_contract:
                type: string
                example: 
              referential_information:
                type: string
                example: 
              created_at:
                type: string
                format: datetime
                example: "2023-09-21 22:04:43"
              updated_at:
                type: string
                format: datetime
                example: "2023-09-21 22:04:43"
              print_ticket:
                type: string
                example: "https://demo.pro5.fastura.app/quotations/print/6012ffb7-a212-4a8b-8839-0e95374a9155/ticket"
              filename:
                type: string
                example: "COT-20-20230921"

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header