openapi: 3.0.3
info:
  title: API de Mensajería
  description: Endpoint para enviar archivos PDF a través de WhatsApp.
  version: 1.0.11

servers:
  - url: https://apievo.qr.buho.la
    description: Servidor de producción

tags:
  - name: api
    description: Enviar PDFs
    externalDocs:
      description: Más
      url: https://apievo.qr.buho.la

paths:
  /api/message/send/pdf:
    post:
      tags:
        - api
      summary: Enviar PDF por WhatsApp
      operationId: enviarPdf
      description: Permite enviar un archivo PDF a un número de WhatsApp.
      requestBody:
        description: Datos necesarios para enviar el PDF.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnviarPDFRequest"
      responses:
        "200":
          description: PDF enviado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Error en la solicitud
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: No autorizado (Token incorrecto o ausente)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    EnviarPDFRequest:
      type: object
      properties:
        number:
          type: string
          example: "123456789"
          description: Número de teléfono en formato internacional sin el "+".
        message:
          type: string
          example: "File PDF"
          description: Mensaje de texto acompañando el PDF.
        file:
          type: string
          format: byte
          example: "JVBERi0xLjQKJeLjz9MK...."
          description: Archivo en formato Base64.
        filename:
          type: string
          example: "file.pdf"
          description: Nombre del archivo.
    
    SuccessResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            key:
              type: object
              properties:
                remoteJid:
                  type: string
                  example: "51123456789@s.whatsapp.net"
                fromMe:
                  type: boolean
                  example: true
                id:
                  type: string
                  example: "BAE51C2115EE6FC0"
            message:
              type: object
              properties:
                documentMessage:
                  type: object
                  properties:
                    url:
                      type: string
                      example: "https://mmg.whatsapp.net/..."
                    mimetype:
                      type: string
                      example: "application/pdf"
                    fileName:
                      type: string
                      example: "file.pdf"
                    caption:
                      type: string
                      example: "File PDF"
            messageTimestamp:
              type: string
              example: "1723397000"
            status:
              type: string
              example: "PENDING"
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Descripción del error"
