openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Notas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/summaries:
    post:
      tags:
        - api
      summary: REGISTRAR Y ENVIAR ANULACIÓN
      description: |  
        Cuando se genera una anulación de boleta, esta no se envía inmediatamente a Sunat. Este documento se envía mediante un resúmen, 
        este puede contener 1 o más boletas, para registrar y enviar el resúmen de anulación puede usar el siguiente servicio, necesitará la url, 
        el token, la fecha de emisión de las boletas que conformarán el resumen, y la data de los documentos.  

        Cuando haya culminado este procedimiento, deberá consultar el ticket del resumen de anulación generado, se explicará en el siguiente punto.  

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** https://empresa1.pro7.uio.la/api/summaries  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt  

      operationId: registrar&enviarAnulacion
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: |
            JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - fastura_auth:
            - write
            - read 
          
# Formato Json de REGISTRAR Y ENVIAR ANULACIÓN
components:
  schemas:
    Pet:
      type: object
      properties:
        fecha_de_emision_de_documentos:
          type: string
          format: date
          example: "2024-11-13"
        codigo_tipo_proceso:
          type: string
          example: "3"
        documentos: 
          type: array
          items:
            type: object
            properties:
              external_id:
                type: string
                example: "2d259905-b4df-4ec0-878c-c5a14f586f17"
              motivo_anulacion:
                type: string
                example: "Se duplicó documento"
        

      required:
        - fecha_de_emision_de_documentos
        - codigo_tipo_proceso
    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            external_id:
              type: string
              example: "0a1382c6-e639-46fc-a8ae-d4659b63c4bd"
            ticket:
              type: string
              example: "1730924660248"
            

  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header