openapi: 3.0.3
info:
  title: Introducción
  description: |-
    Para la implementación de la **Facturación Electrónica**, la SUNAT ha puesto a su disposición diversos manuales y documentos técnicos, los cuales inicialmente son complejos de entender y utilizar.

    La api le permitirá generar diversos documentos electrónicos, y de cada uno obtendrá los 3 archivos indispensables **(XML Firmado, Documento PDF, y CDR)**.

    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generador de facturas
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
      

paths:
  /api/documents/send:
    post:
      tags:
        - api
      summary: ENVIAR FACTURA GENERADA OFFLINE
      description: |
        Para enviar a Sunat la factura generada en modo offline, puede usar el siguiente servicio, necesitará la url, el token y el external_id del documento generado.

        ***Ejemplo:***  
         - **Método:** POST  
         - **URL:** http://demo.fastura.app/api/documents/send  
         - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: facturaGeneradaOffline
      requestBody:
        description: 1. JSON A ENVIAR
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      responses:
        '200':
          description: JSON RESPUESTA
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - petstore_auth:
            - write:pets
            - read:pets
          
# Formato Json de ENVIAR FACTURA GENERADA OFFLINE
components:
  schemas:
    Pet:
      type: object
      properties:
        external_id:
          type: string
          example: "2dded172-cd17-4078-9c88-10a9b1177f2d"

      required:
        - external_id

    Response:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            number:
              type: string
              example: "F001-15"
            filename:
              type: string
              example: "20415963255-01-F001-15"
            external_id:
              type: string
              example: "7d9feb66-16e9-47a9-86fd-ebccdb662678"
        links:
          type: object
          properties:
            cdr:
              type: string
              example: "http://demo26.multifacturalonew.oo:8084/downloads/document/cdr/7d9feb66-16e9-47a9-86fd-ebccdb662678"
        response:
          type: object
          properties:
            code:
              type: string
              example: "0"
            description:
              type: string
              example: "La Factura numero F001-15, ha sido aceptada"
            notes:
              type: array
              items:
                type: string
              example: [] 

      required:
        - data
        - responde

  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header