openapi: 3.0.3
info:
  title: Introducción
  description: |-
    En ocasiones, se producen **errores en la emisión de facturas** a compradores o clientes. Esto provoca que estos errores se deban solventar con diferentes mecanismos, ya que la Ley prohíbe la eliminación de facturas ya emitidas.
    
    Los documentos que se encuentran contemplados son:

    1. Factura  
    2. Boleta  
    3. Nota de Débito  
    4. Nota de Crédito  
    5. Resúmenes  
    6. Anulaciones  
    7. Guia de remisión  
    8. Cotización  
    9. Inventarios  
    10. Productos

  version: 1.0.11
servers:
  - url: https://empresa1.pro7.uio.la
tags:
  - name: api
    description: Generar Cotización
    externalDocs:
      description: Más
      url: https://demo.pro5.fastura.app
paths:
  /api/persons/customers/records:
    get:
      tags:
        - api
      summary: Clientes/Proveedores - Lista paginada
      description: |  
        ***Ejemplo:***  
        - **Método:** GET  
        - **URL:** https://empresa1.pro7.uio.la/api/persons/customers/records 
        - **TOKEN:** HOHYgwd4atPalTxqi2IIspythpLAU7eP239oByfjk9VuveiOpfUTm4Yg0Szt
      operationId: listarProductos
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response'
        '400':
          description: Invalid status value
      security:
        - fastura_auth:
            - write:pets
            - read:pets
          
# Formato Json de LISTAR PRODUCTOS
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
          example: 
        type:
          type: string
          example: "customers"
        identity_document_type_id:
          type: string
          example: "1"
        number:
          type: string
          example: "72346556"
        name:
          type: string
          example: "Pedro Diaz"
        trade_name:
          type: string
          example: "Nombre Comercial"
        country_id:
          type: string
          example: "PE"
        department_id:
          type: string
          example: 
        province_id:
          type: string
          example: 
        district_id:
          type: string
          example: 
        address:
          type: string
          example: "Urb Sesquicentenario Vipol Callao"
        telephone:
          type: string
          example: "954533737"
        condition:
          type: string
          example: 
        state:
          type: string
          example: 
        email:
          type: string
          example: 
        perception_agent:
          type: boolean
          example: false
        percentage_perception:
          type: number
          format: float
          example: 0
        more_address:
          type: array
          items:
            type: string
          example: []
        location_id:
          type: array
          items:
            type: string
          example: []
 
          
      required:
        - number
        - name

        
    Response:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 9
              description:
                type: string
                example: "91241245 - ADMIN1"
              name:
                type: string
                example: "ADMIN1"
              number:
                type: string
                example: "91241245"
              identity_document_type_id:
                type: string
                example: "1"
              identity_document_type_code:
                type: string
                example: 
              address:
                type: string
                example: "callao-ventanilla"
              telephone:
                type: string
                example: "921414124"
              country_id:
                type: string
                example: "PE"
              district_id:
                type: string
                example: "070106"
              email:
                type: string
                example: "joserc@gmail.com"
              enabled:
                type: boolean
                example: true
              selected:
                type: boolean
                example: false
              identity_document_type_description:
                type: string
                example: "DNI"


  requestBodies:
    Pet:
      description: Información...
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
    UserArray:
      description: Lista...
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Response'
  securitySchemes:
    fastura_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://empresa1.pro7.uio.la
          scopes:
            write: Modificar...
            read: Leer..
    api_key:
      type: apiKey
      name: api_key
      in: header